import type { ModuleConfig } from "../models/module.model";

export const moduleToggleOrder: string[] = [
  "pos",
  "salesInvoices",
  "quotations",
  "salesOrders",
  "purchases",
  "salesReturns",
  "payments",
  "ledger",
  "inventory",
  "taxRates",
  "units",
  "categories",
  "brands",
  "reports",
  "roles",
  "users",
  "customers",
  "suppliers",
  "items",
  "sessions",
  "auditLogs",
];

export const moduleConfigs: ModuleConfig[] = [
  { path: "/", title: "Dashboard", endpoint: "/business/dashboard" },
  { path: "/pos", title: "POS / Till", endpoint: "/sales-invoices" },
  { path: "/sales-invoices", title: "Sales Invoices", endpoint: "/sales-invoices" },
  { path: "/quotations", title: "Quotations", endpoint: "/quotations" },
  { path: "/sales-orders", title: "Sales Orders", endpoint: "/sales-orders" },
  { path: "/purchases", title: "Purchases", endpoint: "/purchases" },
  { path: "/sales-returns", title: "Sales Returns", endpoint: "/sales-returns" },
  { path: "/payments", title: "Payments", endpoint: "/payments" },
  { path: "/ledger", title: "Ledger", endpoint: "/ledger" },
  { path: "/inventory", title: "Inventory", endpoint: "/stock-transactions" },
  {
    path: "/tax-rates",
    title: "Tax Rates",
    endpoint: "/tax-rates",
    createFields: [
      { name: "name", label: "Tax name" },
      { name: "ratePercent", label: "Rate %", type: "number" },
      { name: "code", label: "Code" },
    ],
  },
  {
    path: "/units",
    title: "Units",
    endpoint: "/units",
    createFields: [
      { name: "name", label: "Unit name" },
      { name: "symbol", label: "Symbol" },
      { name: "decimalPrecision", label: "Decimal precision", type: "number" },
    ],
  },
  {
    path: "/categories",
    title: "Categories",
    endpoint: "/categories",
    createFields: [
      { name: "name", label: "Category name" },
      { name: "description", label: "Category description" },
      { name: "imageUrl", label: "Category image URL" },
      { name: "subcategories", label: "Subcategories (one per line: title | description | imageUrl)" },
    ],
  },
  {
    path: "/brands",
    title: "Brands",
    endpoint: "/brands",
    createFields: [{ name: "name", label: "Brand name" }],
  },
  { path: "/reports", title: "Reports", endpoint: "/reports/dashboard" },
  { path: "/roles", title: "Roles", endpoint: "/roles" },
  { path: "/users", title: "Users", endpoint: "/users" },
  {
    path: "/customers",
    title: "Customers",
    endpoint: "/customers",
    createFields: [
      { name: "code", label: "Customer code" },
      { name: "name", label: "Customer name" },
      { name: "contactPerson", label: "Contact person" },
      { name: "phone", label: "Phone" },
      { name: "email", label: "Email" },
      { name: "billingAddress", label: "Billing address" },
      { name: "shippingAddress", label: "Shipping address" },
      { name: "taxNo", label: "Tax number" },
      { name: "creditLimit", label: "Credit limit", type: "number" },
      { name: "paymentTermsDays", label: "Payment terms (days)", type: "number" },
      { name: "openingBalance", label: "Opening balance", type: "number" },
      { name: "isActive", label: "Active", type: "boolean" },
      { name: "notes", label: "Notes" },
    ],
  },
  {
    path: "/suppliers",
    title: "Suppliers",
    endpoint: "/suppliers",
    createFields: [
      { name: "code", label: "Supplier code" },
      { name: "name", label: "Supplier name" },
      { name: "contactPerson", label: "Contact person" },
      { name: "phone", label: "Phone" },
      { name: "email", label: "Email" },
      { name: "billingAddress", label: "Billing address" },
      { name: "taxNo", label: "Tax number" },
      { name: "paymentTermsDays", label: "Payment terms (days)", type: "number" },
      { name: "openingBalance", label: "Opening balance", type: "number" },
      { name: "isActive", label: "Active", type: "boolean" },
      { name: "notes", label: "Notes" },
    ],
  },
  {
    path: "/items",
    title: "Items",
    endpoint: "/items",
    createFields: [
      { name: "name", label: "Item name" },
      { name: "code", label: "Code" },
      { name: "sku", label: "SKU" },
      { name: "barcode", label: "Barcode" },
      { name: "imageUrl", label: "Product image URL" },
      { name: "categoryId", label: "Category" },
      { name: "subCategoryId", label: "Subcategory" },
      { name: "subCategory", label: "Subcategory" },
      { name: "brandId", label: "Brand" },
      { name: "description", label: "Description" },
      { name: "primaryUnitId", label: "Primary unit" },
      { name: "secondaryUnitId", label: "Secondary unit" },
      { name: "secondaryToPrimaryFactor", label: "Secondary to primary factor", type: "number" },
      { name: "allowSalesInSecondaryUnit", label: "Allow sales in secondary unit", type: "boolean" },
      { name: "allowPurchaseInSecondaryUnit", label: "Allow purchase in secondary unit", type: "boolean" },
      { name: "allowSecondaryFraction", label: "Allow secondary fraction", type: "boolean" },
      { name: "trackInventory", label: "Track inventory", type: "boolean" },
      { name: "allowNegativeStock", label: "Allow negative stock", type: "boolean" },
      { name: "openingStockPrimary", label: "Opening stock", type: "number" },
      { name: "reorderLevelPrimary", label: "Reorder level", type: "number" },
      { name: "salesPricePrimary", label: "Sales price", type: "number" },
      { name: "purchasePricePrimary", label: "Purchase price", type: "number" },
      { name: "status", label: "Status" },
      { name: "taxable", label: "Taxable", type: "boolean" },
      { name: "defaultTaxRateId", label: "Default tax rate" },
      { name: "notes", label: "Notes" },
    ],
  },
  { path: "/settings", title: "Settings", endpoint: "/settings/customization" },
  { path: "/sessions", title: "Device Sessions", endpoint: "/auth/sessions" },
  { path: "/audit-logs", title: "Audit Logs", endpoint: "/audit-logs" },
];
