export const suggestedPermissions = [
  "business.view",
  "roles.view",
  "roles.create",
  "users.view",
  "users.create",
  "sessions.view",
  "sessions.manage",
  "settings.view",
  "settings.manage",
  "customers.view",
  "customers.create",
  "suppliers.view",
  "suppliers.create",
  "products.view",
  "products.create",
  "units.view",
  "units.create",
  "categories.view",
  "categories.create",
  "subcategories.view",
  "subcategories.create",
  "brands.view",
  "brands.create",
  "taxRates.view",
  "taxRates.create",
  "sales.view",
  "sales.create",
  "sales.non_tax.view",
  "sales.non_tax.create",
  "sales.non_tax.print",
  "purchases.view",
  "purchases.create",
  "returns.view",
  "returns.create",
  "reports.view",
  "inventory.view",
  "inventory.adjust",
  "payments.view",
  "payments.create",
  "refunds.view",
  "refunds.create",
  "ledger.view",
  "audit.view",
] as const;

export const suggestedPermissionsSet = new Set<string>(suggestedPermissions);
